# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='sc_level',
            field=models.TextField(null=True),
        ),
    ]
