# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-12 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_score_sc_level'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeanringClub',
            new_name='LearningClub',
        ),
    ]
